platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

def datalayer
end

def networklayer
end

def uikit
end

def security
end

def protocols
end

def utilities
	pod 'LITSwiftToolkit', path: '../../'
end

def patterns
end

def services 
end

def targetName
	'LITSwiftToolkitExample'
end

target targetName do
#	inhibit_all_warnings!
	use_frameworks!
	datalayer
	networklayer
	uikit
	security
	protocols
	utilities
	patterns
	services
end
